const fontFamily = {
    UrbanistBlack: 'Urbanist-Black',
    UrbanistBlackItalic: 'Urbanist-BlackItalic',
    UrbanistBold: 'Urbanist-Bold',
    UrbanistBoldItalic: 'Urbanist-BoldItalic',
    UrbanistExtraBold: 'Urbanist-ExtraBold',
    UrbanistExtraBoldItalic: 'Urbanist-ExtraBoldItalic',
    UrbanistExtraLight: 'Urbanist-ExtraLight',
    UrbanistExtraLightItalic: 'Urbanist-ExtraLightItalic',
    UrbanistItalic: 'Urbanist-Italic',
    UrbanistLight: 'Urbanist-Light',
    UrbanistLightItalic: 'Urbanist-LightItalic',
    UrbanistMedium: 'Urbanist-Medium',
    UrbanistMediumItalic: 'Urbanist-MediumItalic',
    UrbanistRegular: 'Urbanist-Regular',
    UrbanistSemiBold: 'Urbanist-SemiBold',
    UrbanistSemiBoldItalic: 'Urbanist-SemiBoldItalic',
    UrbanistThin: 'Urbanist-Thin',
    UrbanistThinItalic: 'Urbanist-ThinItalic',
    
    MontserratBlack: 'Montserrat-Black',
    MontserratBlackItalic: 'Montserrat-BlackItalic',
    MontserratBold: 'Montserrat-Bold',
    MontserratBoldItalic: 'Montserrat-BoldItalic',
    MontserratExtraBold: 'Montserrat-ExtraBold',
    MontserratExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    MontserratExtraLight: 'Montserrat-ExtraLight',
    MontserratExtraLightItalic: 'Montserrat-ExtraLightItalic',
    MontserratItalic: 'Montserrat-Italic',
    MontserratLight: 'Montserrat-Light',
    MontserratLightItalic: 'Montserrat-LightItalic',
    MontserratMedium: 'Montserrat-Medium',
    MontserratMediumItalic: 'Montserrat-MediumItalic',
    MontserratRegular: 'Montserrat-Regular',
    MontserratSemiBold: 'Montserrat-SemiBold',
    MontserratSemiBoldItalic: 'Montserrat-SemiBoldItalic',
    MontserratThin: 'Montserrat-Thin',
    MontserratThinItalic: 'Montserrat-ThinItalic'
}

export { fontFamily }